// Bundles the phone UI into one HTML string that the relay serves.
import { readFile, writeFile } from 'node:fs/promises'
import { build, transform } from 'esbuild'

const root = new URL('../', import.meta.url)

const js = await build({
  entryPoints: [new URL('src/ui/main.ts', root).pathname],
  bundle: true,
  format: 'esm',
  target: 'es2020',
  minify: true,
  write: false,
})
const css = await transform(await readFile(new URL('src/ui/style.css', root), 'utf8'), {
  loader: 'css',
  minify: true,
})

const script = js.outputFiles[0].text.replace(/<\/script/gi, '<\\/script')
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light dark"><meta name="robots" content="noindex"><title>pagepad</title><style>${css.code}</style></head><body><main id="app"></main><script type="module">${script}</script></body></html>`

await writeFile(
  new URL('src/ui/generated.ts', root),
  `// Generated by scripts/build-ui.mjs. Do not edit.\nexport const UI_HTML = ${JSON.stringify(html)}\n`,
)
console.log(`phone UI: ${(html.length / 1024).toFixed(1)} KB`)
